# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'home.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 450)
        MainWindow.setStyleSheet("QMainWindow{\n"
" border-image: url(:/pic/image (27).jpg);\n"
"background-color: rgb(0, 255, 255);\n"
"}\n"
"\n"
"\n"
"\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.button_red = QtWidgets.QPushButton(self.centralwidget)
        self.button_red.setGeometry(QtCore.QRect(30, 100, 161, 51))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.button_red.setFont(font)
        self.button_red.setStyleSheet("background-color: rgb(255, 0, 0);")
        self.button_red.setObjectName("button_red")
        self.button_red_2 = QtWidgets.QPushButton(self.centralwidget)
        self.button_red_2.setGeometry(QtCore.QRect(30, 170, 161, 51))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.button_red_2.setFont(font)
        self.button_red_2.setStyleSheet("background-color: rgb(255, 255, 0)")
        self.button_red_2.setObjectName("button_red_2")
        self.button_red_3 = QtWidgets.QPushButton(self.centralwidget)
        self.button_red_3.setGeometry(QtCore.QRect(30, 240, 161, 51))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.button_red_3.setFont(font)
        self.button_red_3.setStyleSheet("background-color: rgb(85, 255, 0)")
        self.button_red_3.setObjectName("button_red_3")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.button_red.setText(_translate("MainWindow", "RED"))
        self.button_red_2.setText(_translate("MainWindow", "YELLOW"))
        self.button_red_3.setText(_translate("MainWindow", "GREEN"))
import picture_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
